apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: imrankhanpathan-com-tls
spec:
  secretName: imrankhanpathan-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: imrankhanpathan.com
  dnsNames:
    - imrankhanpathan.com
    - www.imrankhanpathan.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - imrankhanpathan.com
          - www.imrankhanpathan.com